### ISSUE TITLE
Understanding these callbacks

### ISSUE THREAD

**Issue by jwoertink** [pipobscure/NodeJS-AsteriskManager#20]
I'm trying to call some actions like https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerAction_Agents. When I run this, I get back an object that has the message "Agents will follow". I never actually get any agents listed though. Is there another callback I'm supposed to call, or another event I'm supposed to watch for?

``` javascript
var ami = new AsteriskManager(5038, 'host', 'admin', 'secret', true);
ami.action({action: 'agents', actionid: 1}, function(err, res) {
  console.log(res); //=> { response: 'Success', actionid: '1', message: 'Agents will follow' }
});
```

How do I actually get the agents and their statuses?

**Comment by Rajan1992** [comment]
hey can you please help me to find my peer status? i did this : 


ami.action({action: 'SIPpeerstatus', peer: '1234'}, function(err, res) {
  console.log('this works');
});


but it shows nothing on terminal

my code is : 
var ami = new require('asterisk-manager')('5038','localhost','uname','pwd', true); 

// In case of any connectiviy problems we got you coverd.
ami.keepConnected();

// Listen for any/all AMI events.
ami.on('managerevent', function(evt) {});

// Listen for specific AMI events. A list of event names can be found at
// https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+AMI+Events
ami.on('hangup', function(evt) {});
ami.on('confbridgejoin', function(evt) {});

// Listen for Action responses.
ami.on('response', function(evt) {});

// Perform an AMI Action. A list of actions can be found at
// https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+AMI+Actions
ami.action({action: 'SIPpeerstatus', peer: '7001'}, function(err, res) {
  console.log('this works');
});
