### ISSUE TITLE
action originate response is not "OriginateResponse" 

### ISSUE THREAD

**Issue by wenhuancui** [pipobscure/NodeJS-AsteriskManager#25]
Hi, there is a problem after I send an Originate action (I have also tried setting async:'true' and async:'yes'): when the callee reject or accept the call,  I want to know the event details. But the response given by the api seems not the right one, as per https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerEvent_OriginateResponse.

How can I get full information of OriginateResponse?

**Comment by 2naive** [comment]
@ivahaev Thanks for finding this!

I've had the same problem trying to get the OriginateResponse for my Originate Action (async) with my ActionID this way:

    ami.on('managerevent', function(evt) {
        if(evt.event = 'OriginateResponse')
            console.log(evt);
    });

and I was recieving only frames without ActionID.

*(Actually I somehow got some frames wih OriginateResponse and ActionID, but I cannot reproduce it and it was just only when there was Originate failure)*

@igorescobar I totally agree with @ivahaev that:
that should be 'managerevent' too
AND/OR
return response as callback method (I'm not sure it's possible in ASYNC Originate Action mode?)
AND/OR
at least ami.on('response') handler should be documented in Readme.

Thanks.

**Comment by ivahaev** [comment]
@2naive message **Originate successfully queued** is not **OriginateResponse** event. **OriginateResponse** fired in **response** event with evt.event === 'OriginateResponse'

**Comment by 2naive** [comment]
@ivahaev no, I meant that *Originate successfully queued* is fired in *response* and *action callback*.
For shure: Originate successfully queued != OriginateResponse

**Comment by igorescobar** [comment]
@2naive @ivahaev could you guys propose a PR with your suggestions?

**Comment by 2naive** [comment]
Ok:
https://github.com/pipobscure/NodeJS-AsteriskManager/pull/33
https://github.com/pipobscure/NodeJS-AsteriskManager/pull/34
https://github.com/pipobscure/NodeJS-AsteriskManager/pull/35
https://github.com/pipobscure/NodeJS-AsteriskManager/pull/36

**Comment by igorescobar** [comment]
Could you guys test the version at the master branch?

**Comment by igorescobar** [comment]
@2naive @ivahaev @wenhuancui :+1:

**Comment by igorescobar** [comment]
@2naive @ivahaev @wenhuancui hello?

**Comment by ivahaev** [comment]
I will test it tonight.

**Comment by ivahaev** [comment]
Hmm, callback runs only once

**Comment by ivahaev** [comment]
Yes, callback runs twice.
I think it must be described in documentation, because this is not standard behavior

**Comment by igorescobar** [comment]
@ivahaev what do you mean with "this is not standard behaviour"? 

The response event shouldn't be called?

**Comment by ivahaev** [comment]
No, it should. I thought that to do so:
ami.action(action, actionCallback, responseCallback);

May be it helps for somebody to catch response near action in code. And if it's not necessary to catch response, ignore second callback.
This is just my thoughts :)

**Comment by wenhuancui** [comment]
Great! I will test it tomorrow.

**Comment by igorescobar** [comment]
@wenhuancui I'm running it in production right now... working great so far.

**Comment by wenhuancui** [comment]
Tested. Really great!
The OriginateResponse event can be caught in three places:
1. ami.on('managerevent',. ..)
2. ami.on('response', ...)
3.  the callback of ami.action({}, function()),  although it's in the second time the callback gets called

Maybe you can suggest a best practice :)

**Comment by igorescobar** [comment]
@wenhuancui can you share with us your code snippet used in your test?

**Comment by wenhuancui** [comment]
@igorescobar  It's quite simple to merit a 'share' :)

ami.on('managerevent', function(evt) {
    console.log('manager event:', JSON.stringify(evt));
});
ami.on('response', function(evt) {
   console.log('response event:', JSON.stringify(evt));
});
...
ami.action({
   action:'originate',
   ...
  }, function(err, res) {
    console.log('action callback', err, res);
}
});

action callback will print twice, first one is "queue success" , second is the OriginateResponse
