### ISSUE TITLE
Asterisk AMI v2 (Asterisk 12/13)

### ISSUE THREAD

**Issue by ibrahimab** [pipobscure/NodeJS-AsteriskManager#28]
I can't seem to find if you support Asterisk AMI v2 specification. I am running Asterisk 12 in production and 13 in development. Is it possible to use this library for these versions?

**Comment by unmanner89** [comment]
@igorescobar What Asterix versions NodeJS-AsteriskManager supports?

**Comment by igorescobar** [comment]
@unmanner89 so far 12 and 13.

**Comment by tm1000** [comment]
11,12,13,14,15 (can confirm all)

**Comment by frenzymind** [comment]
Hello. I use Asterisk 17.2.0
This seems not work at this version.
My code:
```
const Ami = require('asterisk-manager');

const HOST = process.env.AMI_HOST || 'localhost';
const PORT = process.env.AMI_PORT || '5038';
const USER = process.env.AMI_USER || 'asterisk';
const PASSWORD = process.env.AMI_PASSWORD || '';

const ami = new Ami(PORT, HOST, USER, PASSWORD, true);

ami.keepConnected();

ami.on('hangup', evt => {
  console.log(evt);
});

module.exports.ami = ami;
```
No any messages in console. Asterisk shows "0 users connected". Manual connect with telnet work.
Can you fix it ?
Thanks.
