### ISSUE TITLE
Auto reconnect isn't working propertly

### ISSUE THREAD

**Issue by igorescobar** [pipobscure/NodeJS-AsteriskManager#30]
@pipobscure Hi!

Turns out that we do have a problem... let me explain... this is a very specific cenario that our AMI can't recover from it.

1 - You start your app, connect to the asterisk...
2 - If you stop asterisk and fire a asterisk event right after the server stopped and error occurs:
```
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:275:12)
    at Object.ManagerAction (/Users/igorescobar/projects/painel/atendimento/node_modules/asterisk-manager/lib/ami.js:267:24)
```

Then our AMI can't recovery by itself. I had to do a workaround to solve the issue in my application:

```javascript
clearInterval(reconnectInterval);
  reconnectInterval = setInterval(function() {
    if (AMIInstance.isConnected() === false) {
      console.log('TRYING TO RECONNECT!');
      setupAMIEvents(AMIConnect());
    }
  }, 1000);
```

@pipobscure Note that when this happen and had to setup my events all over again because I lost my instance.
So two things: 
1 - I can't lose the instance when this kind of error happen.
2 - Can you seed an easier way that we could add this mechanism to our core and make this "connection management" more transparent?

**Comment by 2naive** [comment]
Hi, guys!

Sorry, if I did something wrong, but I have this scenario:
I run default js with

    // In case of any connectiviy problems we got you coverd.
    ami.keepConnected();

restart asterisk while it was connected and got:

    Error: connect ECONNREFUSED
        at errnoException (net.js:904:11)
        at Object.afterConnect [as oncomplete] (net.js:895:19)

Could you please help me to make it try to reconnect on any problem?

Thank you!

**Comment by igorescobar** [comment]
@2naive as any node application you should always handle your exceptions. 

A simple:
```javascript
process.on('uncaughtException', function (err) {
  "use strict";
  console.error(err.stack);
});
```

Should do the trick.

**Comment by 2naive** [comment]
Sorry, but shouldn't it has a some sort of delay at least? Bacause an example you provide (a bit modificated):

    var n_err = 0;
    process.on('uncaughtException', function (err) {
      "use strict";
      n_err++;
      console.error(n_err + ': ' +err.stack);
    });

 and this code:
https://github.com/pipobscure/NodeJS-AsteriskManager/blob/master/lib/ami.js#L208

Gives about:

    94: Error: connect ECONNREFUSED
        at errnoException (net.js:904:11)
        at Object.afterConnect [as oncomplete] (net.js:895:19)
    95: Error: connect ECONNREFUSED
        at errnoException (net.js:904:11)
        at Object.afterConnect [as oncomplete] (net.js:895:19)

at asterisk restart.

Shouldn't this all be handled **inside** AsteriskManager class?

Thank you.

**Comment by igorescobar** [comment]
@2naive could you test this behaviour with our latest release?

**Comment by 2naive** [comment]
Did it, but:
https://github.com/pipobscure/NodeJS-AsteriskManager/issues/40
