### ISSUE TITLE
Object UserEvent has no method 'toLowerCase'

### ISSUE THREAD

**Issue by iatalmid** [pipobscure/NodeJS-AsteriskManager#37]
Hello!

Can you help me with this trouble?
/home/igor/work/web/node_modules/asterisk-manager/lib/ami.js:190
    emits.push(this.emit.bind(this, event.event.toLowerCase(), event));
                                                ^
TypeError: Object UserEvent has no method 'toLowerCase'
    at Object.ManagerEvent (/home/igor/work/web/node_modules/asterisk-manager/lib/ami.js:190:49)
    at EventEmitter.emit (events.js:95:17)
    at Object.ManagerReader (/home/igor/work/web/node_modules/asterisk-manager/lib/ami.js:165:12)

node version 0.10.36
asterisk-manager version 0.1.14

**Comment by igorescobar** [comment]
@iatalmid show me your code :+1:

**Comment by iatalmid** [comment]
> 29 янв. 2015, в 15:29, Igor Escobar <notifications@github.com> написал(а):
> 
> @iatalmid <https://github.com/iatalmid> show me your code 
> 

there are two applications.

One of them send UserEvents. It works well (asterisk-manager 0.1.12).

Other listens events (asterisk-manager 0.1.14). 

And even does't process UserEvent at all.
But when UserEvent comes - it falls. 




> —
> Reply to this email directly or view it on GitHub <https://github.com/pipobscure/NodeJS-AsteriskManager/issues/37#issuecomment-72023409>.
> 



-- 


С ув. Игорь Алюшев

http://kemokiev.org

ICQ: 			312852229
skype: 			iatalmid
sipnet: 			2162395 ext. 2014
Home phone: 		+380(4572)7-57-19
Cell: 			+380(63)578-31-76
Ukraine phone: 	+380(44)374-02-43 ext. 2014
Ukraine mobile: 	+380(93)177-0-257 ext. 2014
USA phone:		+1(516)882-25-03 ext 2014 
Italy phone: 		+39(020)061-37-08 ext. 2014
Poland phone: 	+48(22)382-59-09 ext. 2014
Germany phone: 	+498972101074099 ext. 2014
Russian phone: 	+7(812)458-43-06  ext. 2014
France: 			+33(98)030-05-03

**Comment by igorescobar** [comment]
If you can't show me your code, I can't help you my friend.

**Comment by iatalmid** [comment]
> 11 ôåâð. 2015, â 13:54, Igor Escobar <notifications@github.com> íàïèñàë(à):
> 
> If you can't show me your code, I can't help you my friend.
> 

NP. 
I'd downgraded the manager and everything became well. 

Tnx

**Comment by igorescobar** [comment]
@iatalmid nice your contribution to the community is now "0".

**Comment by iatalmid** [comment]
> 11 февр. 2015, в 19:13, Igor Escobar <notifications@github.com> написал(а):
> 
> @iatalmid <https://github.com/iatalmid> nice your contribution to the community is now "0".
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pipobscure/NodeJS-AsteriskManager/issues/37#issuecomment-73921119>.
> 


What can I say?

In attachment the module, which works with Asterisk.

It does not use userEvents at all.

But if event userEvent comes - I can see this message

Newstate	 ===> {"channel":"SIP/1030-0000007b","channelstate":"4","channelstatedesc":"Ring","calleridnum":"1030","calleridname":"1030","connectedlinenum":"","connectedlinename":"","uniqueid":"1424858076.123"}
Newexten	 ===> {"channel":"SIP/1030-0000007b","context":"cc","extension":"0002177","priority":"1","application":"UserEvent","appdata":"checkNumberConfirm,event: checkNumberConfirm,number: 2177,cli: 1030,channel: SIP/1030-0000007b","uniqueid":"1424858076.123"}
/home/igor/work/web/node_modules/asterisk-manager/lib/ami.js:190
    emits.push(this.emit.bind(this, event.event.toLowerCase(), event));
                                                ^
TypeError: undefined is not a function
    at Object.ManagerEvent (/home/igor/work/web/node_modules/asterisk-manager/lib/ami.js:190:49)
    at EventEmitter.emit (events.js:107:17)
    at Object.ManagerReader (/home/igor/work/web/node_modules/asterisk-manager/lib/ami.js:165:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20) 





-- 


С ув. Игорь Алюшев

http://kemokiev.org

ICQ: 			312852229
skype: 			iatalmid
sipnet: 			2162395 ext. 2014
Home phone: 		+380(4572)7-57-19
Cell: 			+380(63)578-31-76
Ukraine phone: 	+380(44)374-02-43 ext. 2014
Ukraine mobile: 	+380(93)177-0-257 ext. 2014
USA phone:		+1(516)882-25-03 ext 2014 
Italy phone: 		+39(020)061-37-08 ext. 2014
Poland phone: 	+48(22)382-59-09 ext. 2014
Germany phone: 	+498972101074099 ext. 2014
Russian phone: 	+7(812)458-43-06  ext. 2014
France: 			+33(98)030-05-03
