### ISSUE TITLE
Delay before reconnect

### ISSUE THREAD

**Issue by 2naive** [pipobscure/NodeJS-AsteriskManager#40]
Hi!

This https://github.com/pipobscure/NodeJS-AsteriskManager/blob/master/lib/ami.js#L238 causes infinite loop of reconnects. Moreover, If you try to log with 

```
ami.on('error', function(evt) {
    console.log(evt);
});
```

You will get blowing up log files.

I think we should add a delay before reconnect

**Comment by pipobscure** [comment]
#50
