### ISSUE TITLE
Action: Queues failed

### ISSUE THREAD

**Issue by Seafnox** [pipobscure/NodeJS-AsteriskManager#41]
When sending action 'Queues' on server, result are not comming because parsing are failed

Code:
ami.action({
    "action":"Queues"
}, function(err, res){
    console.log(err, res);
});

Server answer:
QUEUE_NAME1 has 0 calls (max unlimited) in 'ringall' strategy (2s holdtime, 4s talktime), W:0, C:2, A:3, SL:100.0% within 60s
   Members: 
      111 (Local/111@from-internal/n from Local/111@from-internal/n) with penalty 2 (ringinuse disabled) (realtime) (paused) (Not in use) has taken no calls yet
      222 (Local/222@from-internal/n from Local/222@from-internal/n) with penalty 3 (ringinuse disabled) (realtime) (Not in use) has taken 2 calls (last was 10 secs ago)
   No Callers

QUEUE_NAME2 has 0 calls (max unlimited) in 'ringall' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0% within 0s
   No Members
   No Callers

**Comment by pipobscure** [comment]
Feel free to send PR
