### ISSUE TITLE
event.event.toLowerCase is not a function

### ISSUE THREAD

**Issue by iatalmid** [pipobscure/NodeJS-AsteriskManager#44]
/srv/main/node_modules/asterisk-manager/lib/ami.js:191

when I add before this line console.log(event.event), I've received
ChallengeSent
DeviceStateChange
Newchannel
VarSet
VarSet
VarSet
Newstate
SuccessfulAuth
Newexten
[ 'UserEvent' ]

so, UserEvent caused exception

**Comment by RShadowhand** [comment]
try the following instead:
var util = require('util');

util.log(event.event);

**Comment by pipobscure** [comment]
Should be fixed by #45
