### ISSUE TITLE
example please

### ISSUE THREAD

**Issue by ezekel** [pipobscure/NodeJS-AsteriskManager#55]
Hi, can you please show some simple example on how to use this plugins.
do I need to create client.js for this ? .I want to use your plugins but I don't know how to get started, hopefully you can create simple example like conference.

please help me how to achieve this.

Thank you in advance.

**Comment by igorescobar** [comment]
Take a look into this:
http://www.igorescobar.com/blog/2014/08/13/working-with-asterisk-and-node-js/

Hope it helps.


Enviado do meu iPhone

**Comment by ezekel** [comment]
@igorescobar ,

Thank you for the quick reply..can I ask this part code here 

```
ami.on('confbridgejoin', function(evt) {});

```
how to use that confbrigejoin ?

also can you show me how to let one extension to join in conference.

is this code where I can let the extension to join the conference , mute  or .etc.. ?

```

ami.action({
  'action':'originate',
  'channel': "SIP/1234",
  'exten': '1143224321',
  'context': 'from-internal',
  'priority': '1'
}, function(err, res) {});

```

Thank you in advance.

**Comment by igorescobar** [comment]
All you need is to read the docs:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_ConfbridgeJoin

Regards,
Igor Escobar

*Software Engineer*
+ http://blog.igorescobar.com
+ http://www.igorescobar.com
+ @igorescobar <http://www.twitter.com/igorescobar>

**Comment by ezekel** [comment]
@igorescobar ,

Thank you for the quick reply.

for example I have 123 extension

How can I join him to the conference ? ex: conference number is 145
so In your api. I will use this

```
ami.on('confbridgejoin', function(evt) {
   
   // I will supply here some parameters base on the docs you have linked to me. ?

});

```



Thank you in advance.
